### ISSUE TITLE
canot gen.SESSION

### ISSUE THREAD

**Issue by justinthoms** [TheWhatsBot/WhatsBot#2]
canot gen SESSION

ERROR:

        at onClose (/data/data/com.termux/files/home/WhatsBot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at ChildProcess.<anonymous> (/data/data/com.termux/files/home/WhatsBot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:185:85)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7058) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7058) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by cachecleanerjeet** [comment]
You can't generate it on termux, chomium should be open to generate that and it can't possible on your termux. However you can use repl.it i tested there.
Check wiki for more info.

**Comment by cachecleanerjeet** [comment]
I hope this issue has been resolved. So, closing this issue, if not resolved feel free to reopen it 👍
